<script>
	import FixtureListItem from '$lib/components/FixtureListItem.svelte';
	import Note from '$lib/components/Note.svelte';
	import { startLoading, staticApiData, stopLoading, userState } from '$lib/state/+state.svelte';
	import { displayDate, displayTeamName, shuffleList } from '$lib/utils';
	import { hplFetch } from '$lib/utils/api';
	import { onMount } from 'svelte';

	let teams = $derived.by(() => staticApiData?.teams);
	let fixtures = $state([]);
	let storedFixtures = $state([]);
	const currentSeason = staticApiData?.seasons?.find((season) =>
		['Scheduled', 'Active'].includes(season.status)
	);
	const defaultStartDate = '2026-03-21';
	const TIMES = ['9:30 AM', '2:30 PM'];
	let leagueStartDate = $state(defaultStartDate);

	onMount(async () => {
		try {
			startLoading('Fetching fixtures...');
			const fixturesResponse = await hplFetch(fetch, '/fixtures', 'GET');
			fixtures = await fixturesResponse.json();
			if (fixtures.length === 0) {
				// get from stored previous generated fixtures
				const hplAutoGeneratedFixtures = localStorage.getItem('hpl-auto-fixtures');
				storedFixtures = JSON.parse(hplAutoGeneratedFixtures) || [];
				leagueStartDate = storedFixtures[0].match_date;
			} else {
				leagueStartDate = fixtures[0].match_date;
			}
		} catch (e) {
			alert(e.message);
		} finally {
			stopLoading();
		}
	});

	async function generateFixtures(reShuffle = false) {
		if (!teams || teams.length < 2) return;
		try {
			startLoading('Generating fixtures...');
			// rank based on seed
			let teamList = [...teams].sort((t1, t2) => Number(t1.seed_rank) - Number(t2.seed_rank));
			if (reShuffle) {
				teamList = shuffleList(teamList);
				fixtures = [];
			}
			const n = teamList.length;
			const hasBye = n % 2 !== 0;
			if (hasBye) {
				teamList.push({ id: 'bye', name: 'bye' });
			}
			const totalTeams = teamList.length;
			const rounds = totalTeams - 1;
			const half = totalTeams / 2;

			let leg1 = [];
			// leg 1 round robin
			for (let round = 0; round < rounds; round++) {
				for (let i = 0; i < half; i++) {
					const teamA = teamList[i];
					const teamB = teamList[totalTeams - 1 - i];
					if (teamA.id !== 'bye' && teamB.id !== 'bye') {
						leg1.push({
							team_a: teamA,
							team_b: teamB,
							leg: 1
						});
					}
				}
				teamList.splice(1, 0, teamList.pop());
			}
			// leg 2
			const leg2 = leg1.map((f) => ({
				team_a: f.team_b,
				team_b: f.team_a,
				leg: 2
			}));

			const all = [...leg1, ...leg2];

			let date = leagueStartDate ? new Date(leagueStartDate) : new Date(defaultStartDate);
			let counter = 0;

			setTimeout(() => {
				fixtures = all.map((f, idx) => {
					const isMorning = counter % 2 === 0;
					const match_date = date.toISOString().substring(0, 10);
					counter++;
					if (counter % 2 === 0) {
						date.setDate(date.getDate() + 1);
					}
					return {
						match_number: idx + 1,
						team_a: f.team_a.id,
						team_b: f.team_b.id,
						leg: f.leg,
						match_date,
						start_time: isMorning ? TIMES[0] : TIMES[1],
						venue: 'HADAGALI',
						season_id: currentSeason.id
					};
				});

				setFixturesToLocalStorage(fixtures);
				stopLoading();
			}, 1000);
		} catch (e) {
			console.log(e.message);
			window.location.href = '/';
		}
	}

	function setFixturesToLocalStorage(fixtures) {
		localStorage.setItem('hpl-auto-fixtures', JSON.stringify(fixtures));
		storedFixtures = fixtures;
	}
</script>

{#if !userState.id && fixtures.length === 0}
	<Note text="Please comeback  soon, fixtures will be announced soon" />
{:else if userState.id && teams?.length && (storedFixtures?.length === 0 || storedFixtures?.length > 1)}
	<div class="w-full">
		<h1 class="text-xl font-bold mb-4 text-gray-800 text-center">Admin Fixture Generator</h1>
		<div class="flex justify-between items-center border-b-1 mb-5">
			<div class="date-container flex flex-col gap-2 mb-2">
				<label for="startdate" class="text-sm text-gray-800">Pick league start day</label>
				<input type="date" bind:value={leagueStartDate} id="startdate" class="fit-content" />
			</div>
			<div class="text-center">
				<button
					class="px-4 py-2 bg-blue-500 text-white rounded-lg shadow-lg"
					onclick={() => {
						if (storedFixtures?.length) {
							generateFixtures(true);
						} else {
							generateFixtures();
						}
					}}
				>
					{storedFixtures?.length ? 'Regenerate' : 'Generate Fixtures'}
				</button>
			</div>
		</div>
		<div class="space-y-4">
			{#each storedFixtures as match (match.match_number)}
				<FixtureListItem {match} {teams} />
			{/each}
		</div>
	</div>
{:else if fixtures.length > 0}
	<div class="space-y-4">
		{#each fixtures as match (match.match_number)}
			<FixtureListItem {match} {teams} />
		{/each}
	</div>
{/if}
